use anchor_lang::prelude::*;
use anchor_lang::solana_program::{
    ed25519_program,
    sysvar::instructions::{self, load_instruction_at_checked},
};
use groth16_solana::groth16::Groth16Verifier;
use policy_registry::state::PolicyAccount;
use crate::groth16_vk::{APERTURE_PAYMENT_VK, PAYMENT_NR_INPUTS};
use crate::state::{ProofRecord, ComplianceStatus, OperatorState};

/// Adım 8c — MPP B-flow verifier.
///
/// Counterpart to verify_payment_proof_v2 for payments that settled through
/// Stripe instead of an SPL Token-2022 transfer. The trust model is "Stripe
/// is a trusted oracle" — the compliance-api signs every verified Stripe
/// PaymentIntent's canonical Poseidon hash with its MPP_AUTHORITY ed25519
/// keypair, and the on-chain verifier checks that signature inside the same
/// transaction (via the Solana ed25519 native precompile).
///
/// What this instruction guarantees once it succeeds:
///   1. The Groth16 proof is cryptographically sound and the policy_data_hash
///      matches the on-chain PolicyAccount (Adım 5 invariants).
///   2. The proof carries a NON-ZERO stripe_receipt_hash — it is a B-flow
///      proof, not a Solana-flow one (preventing cross-flow replay).
///   3. The compliance-api ed25519 signature on that exact stripe_receipt_hash
///      is present in the same transaction at instruction index 0 (the
///      pre-Anchor "ed25519 verify" instruction Solana exposes via the
///      ed25519_program native precompile).
///   4. daily_spent has been atomically advanced by amount_lamports — there
///      is no transfer-hook in this flow, so the increment lives here.
///
/// Replay protection: the ProofRecord PDA is seeded by policy_data_hash, so
/// every (policy, payment) tuple gets a unique PDA. Anchor's `init` (not
/// `init_if_needed`) on the proof_record account would fail-closed on a
/// second submission — but we keep `init_if_needed` for parity with v2 and
/// rely on the `consumed` flag to refuse replays.
#[derive(Accounts)]
#[instruction(
    proof_a: [u8; 64],
    proof_b: [u8; 128],
    proof_c: [u8; 64],
    public_inputs: [[u8; 32]; PAYMENT_NR_INPUTS],
)]
pub struct VerifyMppPaymentProof<'info> {
    #[account(
        init_if_needed,
        payer = payer,
        space = 8 + ProofRecord::INIT_SPACE,
        seeds = [b"proof", operator.key().as_ref(), &public_inputs[1]],
        bump,
    )]
    pub proof_record: Account<'info, ProofRecord>,

    #[account(
        init_if_needed,
        payer = payer,
        space = 8 + ComplianceStatus::INIT_SPACE,
        seeds = [b"compliance", operator.key().as_ref()],
        bump,
    )]
    pub compliance_status: Account<'info, ComplianceStatus>,

    #[account(
        init_if_needed,
        payer = payer,
        space = 8 + OperatorState::INIT_SPACE,
        seeds = [b"operator_state", operator.key().as_ref()],
        bump,
    )]
    pub operator_state: Account<'info, OperatorState>,

    #[account(
        owner = policy_registry::ID,
        constraint = policy_account.active @ MppVerifierError::PolicyInactive,
        constraint = policy_account.operator == operator_account.key()
            @ MppVerifierError::PolicyOperatorMismatch,
    )]
    pub policy_account: Account<'info, PolicyAccount>,

    #[account(
        owner = policy_registry::ID,
        constraint = operator_account.authority == operator.key()
            @ MppVerifierError::PolicyOperatorMismatch,
    )]
    pub operator_account: Account<'info, policy_registry::state::OperatorAccount>,

    pub operator: Signer<'info>,

    #[account(mut)]
    pub payer: Signer<'info>,

    /// CHECK: address-checked against the well-known Sysvar Instructions ID
    /// so we can load the preceding ed25519 verify instruction in the same tx.
    #[account(address = instructions::ID)]
    pub instructions_sysvar: AccountInfo<'info>,

    pub system_program: Program<'info, System>,
}

const TIMESTAMP_TOLERANCE_SECONDS: i64 = 60;

/// Expected ed25519 signer for every Stripe receipt attestation. This is the
/// public key half of the compliance-api's MPP_AUTHORITY_KEYPAIR_BASE58 env.
/// Pinning it at compile time means the verifier cannot be tricked into
/// trusting an attacker-controlled signer; a key rotation is a program
/// upgrade event, intentionally heavyweight.
///
/// Generated by scripts/deploy/mpp-authority.json. The matching secret key
/// must be set as MPP_AUTHORITY_KEYPAIR_BASE58 in the compliance-api .env.
const MPP_AUTHORITY_PUBKEY: Pubkey = anchor_lang::solana_program::pubkey!(
    "46i1zhvWsXrA2Ny1PWe3gGmRWNNy4RpkYrBuUxe5cfyq"
);

fn read_u64_from_field(bytes: &[u8; 32]) -> Result<u64> {
    for &b in &bytes[0..24] {
        if b != 0 {
            return err!(MppVerifierError::PublicInputOverflow);
        }
    }
    let mut buf = [0u8; 8];
    buf.copy_from_slice(&bytes[24..32]);
    Ok(u64::from_be_bytes(buf))
}

fn read_i64_from_field(bytes: &[u8; 32]) -> Result<i64> {
    let v = read_u64_from_field(bytes)?;
    if v > i64::MAX as u64 {
        return err!(MppVerifierError::PublicInputOverflow);
    }
    Ok(v as i64)
}

/// Parses a Solana ed25519 native-program verify instruction and asserts it
/// authenticates `expected_message` under `expected_signer`. The Solana
/// ed25519_program data layout is:
///
///   offset 0  : u8       num_signatures        (must be 1)
///   offset 1  : u8       padding
///   offset 2  : u16 LE   signature_offset
///   offset 4  : u16 LE   signature_instruction_index   (0xFFFF = current ix)
///   offset 6  : u16 LE   public_key_offset
///   offset 8  : u16 LE   public_key_instruction_index  (0xFFFF = current ix)
///   offset 10 : u16 LE   message_data_offset
///   offset 12 : u16 LE   message_data_size
///   offset 14 : u16 LE   message_instruction_index     (0xFFFF = current ix)
///   ...        public_key (32) || signature (64) || message (variable)
///
/// We require all three "instruction_index" fields to be 0xFFFF so the
/// signing material lives entirely inside this same instruction's data —
/// otherwise an attacker could redirect the lookup at a different ix that
/// happened to contain controlled bytes.
fn assert_ed25519_attestation(
    ed25519_data: &[u8],
    expected_signer: &Pubkey,
    expected_message: &[u8; 32],
) -> Result<()> {
    if ed25519_data.len() < 16 {
        return err!(MppVerifierError::Ed25519InstructionMalformed);
    }
    if ed25519_data[0] != 1 {
        return err!(MppVerifierError::Ed25519InstructionMalformed);
    }

    let read_u16 = |offset: usize| -> u16 {
        u16::from_le_bytes([ed25519_data[offset], ed25519_data[offset + 1]])
    };
    let signature_offset = read_u16(2) as usize;
    let signature_ix_index = read_u16(4);
    let public_key_offset = read_u16(6) as usize;
    let public_key_ix_index = read_u16(8);
    let message_offset = read_u16(10) as usize;
    let message_size = read_u16(12) as usize;
    let message_ix_index = read_u16(14);

    if signature_ix_index != 0xFFFF
        || public_key_ix_index != 0xFFFF
        || message_ix_index != 0xFFFF
    {
        return err!(MppVerifierError::Ed25519InstructionRedirection);
    }

    if public_key_offset + 32 > ed25519_data.len()
        || signature_offset + 64 > ed25519_data.len()
        || message_offset + message_size > ed25519_data.len()
    {
        return err!(MppVerifierError::Ed25519InstructionMalformed);
    }

    if message_size != 32 {
        return err!(MppVerifierError::Ed25519MessageSizeMismatch);
    }

    let signer_bytes = &ed25519_data[public_key_offset..public_key_offset + 32];
    if signer_bytes != expected_signer.as_ref() {
        return err!(MppVerifierError::Ed25519SignerMismatch);
    }

    let message_bytes = &ed25519_data[message_offset..message_offset + message_size];
    if message_bytes != expected_message {
        return err!(MppVerifierError::Ed25519MessageMismatch);
    }

    Ok(())
}

pub fn handler(
    ctx: Context<VerifyMppPaymentProof>,
    proof_a: [u8; 64],
    proof_b: [u8; 128],
    proof_c: [u8; 64],
    public_inputs: [[u8; 32]; PAYMENT_NR_INPUTS],
) -> Result<()> {
    // 1. Groth16 cryptographic verification.
    let mut verifier = Groth16Verifier::<PAYMENT_NR_INPUTS>::new(
        &proof_a,
        &proof_b,
        &proof_c,
        &public_inputs,
        &APERTURE_PAYMENT_VK,
    )
    .map_err(|_| error!(MppVerifierError::MalformedProof))?;
    verifier
        .verify()
        .map_err(|_| error!(MppVerifierError::ProofVerificationFailed))?;

    // 2. is_compliant must be 1.
    let mut expected_compliant = [0u8; 32];
    expected_compliant[31] = 1;
    if public_inputs[0] != expected_compliant {
        return err!(MppVerifierError::NotCompliant);
    }

    // 3. policy_data_hash byte-equality with on-chain PolicyAccount.
    let proof_policy_hash = public_inputs[1];
    if proof_policy_hash != ctx.accounts.policy_account.policy_data_hash {
        return err!(MppVerifierError::PolicyHashMismatch);
    }

    // 4. timestamp drift.
    let clock = Clock::get()?;
    let now = clock.unix_timestamp;
    let proof_unix = read_i64_from_field(&public_inputs[8])?;
    if (now - proof_unix).abs() > TIMESTAMP_TOLERANCE_SECONDS {
        return err!(MppVerifierError::TimestampOutOfRange);
    }

    // 5. stripe_receipt_hash MUST be non-zero — this is the MPP flow.
    let stripe_hash_bytes = public_inputs[9];
    if stripe_hash_bytes == [0u8; 32] {
        return err!(MppVerifierError::StripeReceiptMissing);
    }

    // 6. Inspect the ed25519 verify instruction that the client placed at
    //    index 0 of this transaction. It must attest the Stripe receipt
    //    Poseidon hash under the compliance-api's MPP_AUTHORITY pubkey.
    let ix_zero = load_instruction_at_checked(0, &ctx.accounts.instructions_sysvar)
        .map_err(|_| error!(MppVerifierError::Ed25519InstructionMissing))?;
    if ix_zero.program_id != ed25519_program::ID {
        return err!(MppVerifierError::Ed25519InstructionMissing);
    }
    assert_ed25519_attestation(
        &ix_zero.data,
        &MPP_AUTHORITY_PUBKEY,
        &stripe_hash_bytes,
    )?;

    // 7. daily_spent_before parity check + atomic increment. Mirrors
    //    record_payment's logic so the operator's daily budget is enforced
    //    end-to-end without a transfer-hook in the loop.
    let amount = read_u64_from_field(&public_inputs[4])?;
    let proof_daily_spent = read_u64_from_field(&public_inputs[7])?;

    {
        let state = &mut ctx.accounts.operator_state;
        if state.operator == Pubkey::default() {
            state.operator = ctx.accounts.operator.key();
            state.day_start_unix = OperatorState::day_start_for(now);
            state.bump = ctx.bumps.operator_state;
        }
        let onchain_daily_spent = if state.is_new_day(now) {
            0u64
        } else {
            state.daily_spent_lamports
        };
        if proof_daily_spent != onchain_daily_spent {
            return err!(MppVerifierError::DailySpentMismatch);
        }
        if state.is_new_day(now) {
            state.daily_spent_lamports = 0;
            state.day_start_unix = OperatorState::day_start_for(now);
        }
        state.daily_spent_lamports = state
            .daily_spent_lamports
            .checked_add(amount)
            .ok_or(error!(MppVerifierError::DailySpentOverflow))?;
        state.total_lifetime_payments = state.total_lifetime_payments.saturating_add(1);
        // pending_proof_hash is intentionally NOT set: the MPP flow has no
        // matching SPL transfer to consume it later.
    }

    // 8. Persist the proof record. `consumed=true` from the start because
    //    nothing else will come along to consume it.
    let recipient_field = public_inputs[2];
    let token_field = public_inputs[5];
    let mut recipient = [0u8; 32];
    recipient[0..16].copy_from_slice(&recipient_field[16..32]);
    recipient[16..32].copy_from_slice(&public_inputs[3][16..32]);
    let mut token_mint = [0u8; 32];
    token_mint[0..16].copy_from_slice(&token_field[16..32]);
    token_mint[16..32].copy_from_slice(&public_inputs[6][16..32]);

    let proof = &mut ctx.accounts.proof_record;
    proof.operator = ctx.accounts.operator.key();
    proof.policy_id = ctx.accounts.policy_account.key().to_bytes();
    proof.proof_hash = proof_policy_hash;
    proof.image_id = [0u32; 8];
    proof.journal_digest = proof_policy_hash;
    proof.timestamp = now;
    proof.verified = true;
    proof.consumed = true;
    proof.recipient = recipient;
    proof.token_mint = token_mint;
    proof.amount_lamports = amount;
    proof.bump = ctx.bumps.proof_record;

    let status = &mut ctx.accounts.compliance_status;
    status.operator = ctx.accounts.operator.key();
    status.is_compliant = true;
    status.last_proof_hash = proof_policy_hash;
    status.last_verified_at = now;
    status.total_proofs = status.total_proofs.saturating_add(1);
    status.bump = ctx.bumps.compliance_status;

    msg!(
        "MPP proof verified: operator={}, amount={}, daily_spent={}, total_proofs={}",
        ctx.accounts.operator.key(),
        amount,
        ctx.accounts.operator_state.daily_spent_lamports,
        status.total_proofs
    );
    Ok(())
}

#[error_code]
pub enum MppVerifierError {
    #[msg("Groth16 proof is malformed")]
    MalformedProof,
    #[msg("Groth16 proof verification failed")]
    ProofVerificationFailed,
    #[msg("Public input overflows u64/i64")]
    PublicInputOverflow,
    #[msg("Proof claims a non-compliant outcome — only compliant proofs may be persisted")]
    NotCompliant,
    #[msg("Proof's policy_data_hash does not match the on-chain PolicyAccount commitment")]
    PolicyHashMismatch,
    #[msg("Policy is not active on-chain")]
    PolicyInactive,
    #[msg("Policy account is not registered to the signing operator")]
    PolicyOperatorMismatch,
    #[msg("Proof's daily_spent_before does not match OperatorState's effective daily spend")]
    DailySpentMismatch,
    #[msg("Proof timestamp drifted outside the allowed window")]
    TimestampOutOfRange,
    #[msg("MPP proof requires a non-zero stripe_receipt_hash public input")]
    StripeReceiptMissing,
    #[msg("Transaction is missing the ed25519 verify instruction at index 0")]
    Ed25519InstructionMissing,
    #[msg("Ed25519 verify instruction has malformed offsets/lengths")]
    Ed25519InstructionMalformed,
    #[msg("Ed25519 verify instruction redirects to another instruction's data")]
    Ed25519InstructionRedirection,
    #[msg("Ed25519 message must be exactly 32 bytes (the receipt hash)")]
    Ed25519MessageSizeMismatch,
    #[msg("Ed25519 signer is not the configured MPP_AUTHORITY")]
    Ed25519SignerMismatch,
    #[msg("Ed25519 message does not match the proof's stripe_receipt_hash")]
    Ed25519MessageMismatch,
    #[msg("daily_spent_lamports would overflow u64")]
    DailySpentOverflow,
}
