'use client';

/**
 * ComplianceStatsRow — top of the Compliance tab. Shows lifetime KPIs that
 * matter for an auditor or compliance officer at a glance.
 */

import { useMemo } from 'react';
import { Stamp, Anchor, Layers, AlertOctagon } from 'lucide-react';
import type { Attestation } from '@/lib/api';
import { MetricCard } from '../overview/MetricCard';

export function ComplianceStatsRow({
  attestations,
}: {
  attestations: readonly Attestation[];
}) {
  const stats = useMemo(() => {
    const total = attestations.length;
    const anchored = attestations.filter((a) => Boolean(a.tx_signature)).length;
    let totalPayments = 0;
    let totalViolations = 0;
    for (const a of attestations) {
      totalPayments += Number(a.total_payments) || 0;
      totalViolations += Number(a.policy_violations) || 0;
    }
    return { total, anchored, totalPayments, totalViolations };
  }, [attestations]);

  const anchoredPct =
    stats.total > 0 ? Math.round((stats.anchored / stats.total) * 100) : 0;

  return (
    <section className="grid grid-cols-2 lg:grid-cols-4 gap-4">
      <MetricCard
        label="Batch Attestations"
        value={stats.total.toLocaleString()}
        icon={Stamp}
        hint="Lifetime — generated by this operator"
      />
      <MetricCard
        label="On-chain Anchored"
        value={`${anchoredPct}%`}
        icon={Anchor}
        hint={`${stats.anchored} of ${stats.total} have a tx signature`}
      />
      <MetricCard
        label="Total Payments Covered"
        value={stats.totalPayments.toLocaleString()}
        icon={Layers}
        hint="Sum across every attestation period"
      />
      <MetricCard
        label="Policy Violations"
        value={stats.totalViolations.toLocaleString()}
        icon={AlertOctagon}
        hint="Aggregate across all attested batches"
      />
    </section>
  );
}
